// <auto-generated />
using APBD_Projekt1.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_Projekt1.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_Projekt1.Models.CompanyClient", b =>
                {
                    b.Property<int>("CompanyClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyClientId"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KRSNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("CompanyClientId");

                    b.ToTable("CompanyClients");

                    b.HasData(
                        new
                        {
                            CompanyClientId = 1,
                            Adress = "Różana 3",
                            Email = "firma1@op.pl",
                            KRSNumber = "0123456789",
                            Name = "Firma1",
                            PhoneNumber = 0
                        },
                        new
                        {
                            CompanyClientId = 2,
                            Adress = "Konwaliowa 3",
                            Email = "firma2@o2.pl",
                            KRSNumber = "1111111111",
                            Name = "Firma2",
                            PhoneNumber = 898989898
                        });
                });

            modelBuilder.Entity("APBD_Projekt1.Models.IndividualClient", b =>
                {
                    b.Property<int>("IndividualClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndividualClientId"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("IndividualClientId");

                    b.ToTable("IndividualClients");

                    b.HasData(
                        new
                        {
                            IndividualClientId = 1,
                            Adress = "Wrzosowa 1",
                            Email = "jankowalski@gmail.com",
                            FirstName = "Jan",
                            IsDeleted = false,
                            LastName = "Kowalski",
                            PESEL = "01010101010",
                            PhoneNumber = 511111111
                        },
                        new
                        {
                            IndividualClientId = 2,
                            Adress = "Tulipanowa 1",
                            Email = "nowak@gmail.com",
                            FirstName = "Kazimierz",
                            IsDeleted = false,
                            LastName = "Nowak",
                            PESEL = "01010101010",
                            PhoneNumber = 123124125
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
